# Generated by Django 3.2.25 on 2025-09-01 14:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='Employé', max_length=50)),
            ],
            options={
                'default_related_name': 'roles',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quartier', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=7)),
                ('jour_1', models.IntegerField(default=0)),
                ('jour_2', models.IntegerField(default=0)),
                ('jour_3', models.IntegerField(default=0)),
                ('jour_4', models.IntegerField(default=0)),
                ('jour_5', models.IntegerField(default=0)),
                ('jour_6', models.IntegerField(default=0)),
                ('jour_7', models.IntegerField(default=0)),
                ('jour_8', models.IntegerField(default=0)),
                ('jour_9', models.IntegerField(default=0)),
                ('jour_10', models.IntegerField(default=0)),
                ('jour_11', models.IntegerField(default=0)),
                ('jour_12', models.IntegerField(default=0)),
                ('jour_13', models.IntegerField(default=0)),
                ('jour_14', models.IntegerField(default=0)),
                ('jour_15', models.IntegerField(default=0)),
                ('jour_16', models.IntegerField(default=0)),
                ('jour_17', models.IntegerField(default=0)),
                ('jour_18', models.IntegerField(default=0)),
                ('jour_19', models.IntegerField(default=0)),
                ('jour_20', models.IntegerField(default=0)),
                ('jour_21', models.IntegerField(default=0)),
                ('jour_22', models.IntegerField(default=0)),
                ('jour_23', models.IntegerField(default=0)),
                ('jour_24', models.IntegerField(default=0)),
                ('jour_25', models.IntegerField(default=0)),
                ('jour_26', models.IntegerField(default=0)),
                ('jour_27', models.IntegerField(default=0)),
                ('jour_28', models.IntegerField(default=0)),
                ('jour_29', models.IntegerField(default=0)),
                ('jour_30', models.IntegerField(default=0)),
                ('jour_31', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'default_related_name': 'tasks',
            },
        ),
        migrations.CreateModel(
            name='TaskType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'default_related_name': 'task_types',
            },
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actif', models.BooleanField(default=True)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utilisateurs', to='marafik_app.role')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='utilisateur', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'default_related_name': 'utilisateurs',
            },
        ),
        migrations.CreateModel(
            name='TaskHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Création'), ('UPDATE', 'Modification'), ('DELETE', 'Suppression')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_histories', to='marafik_app.task')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_histories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'default_related_name': 'task_histories',
            },
        ),
        migrations.AddField(
            model_name='task',
            name='task_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='marafik_app.tasktype'),
        ),
        migrations.CreateModel(
            name='FichierExcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_fichier', models.CharField(max_length=200)),
                ('fichier_path', models.CharField(max_length=500)),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('type_utilisation', models.CharField(max_length=100)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichiers_excel', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'default_related_name': 'fichiers_excel',
            },
        ),
        migrations.CreateModel(
            name='HiddenTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_hidden', models.BooleanField(default=False)),
                ('hidden_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marafik_app.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'task')},
            },
        ),
    ]
